### ISSUE TITLE
detected unhandled Python exception in '/usr/bin/celery'

### ISSUE THREAD

**Issue by sjnadas** [openbacchus/bacchus#26]
console: 
[root@cs-test3 logs]# systemctl status nginx
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-07-10 09:35:49 EDT; 5h 43min ago
  Process: 14349 ExecStart=/usr/sbin/nginx (code=exited, status=0/SUCCESS)
  Process: 14346 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=0/SUCCESS)
  Process: 14344 ExecStartPre=/usr/bin/rm -f /run/nginx.pid (code=exited, status=0/SUCCESS)
 Main PID: 14351 (nginx)
    Tasks: 3
   CGroup: /system.slice/nginx.service
           ├─14351 nginx: master process /usr/sbin/nginx
           ├─14352 nginx: worker process
           └─14353 nginx: worker process

Jul 10 09:35:49 cs-test3.bu.edu systemd[1]: Starting The nginx HTTP and reverse proxy server...
Jul 10 09:35:49 cs-test3.bu.edu nginx[14346]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Jul 10 09:35:49 cs-test3.bu.edu nginx[14346]: nginx: configuration file /etc/nginx/nginx.conf test is successful
Jul 10 09:35:49 cs-test3.bu.edu systemd[1]: Started The nginx HTTP and reverse proxy server.
[root@cs-test3 logs]# systemctl status bacchus
● bacchus.service - Bacchus Service
   Loaded: loaded (/etc/systemd/system/bacchus.service; enabled; vendor preset: disabled)
   Active: active (exited) since Tue 2018-07-10 09:35:49 EDT; 5h 44min ago
  Process: 14377 ExecStart=/bin/bash /opt/bacchus/tools/start_bacchus.sh (code=exited, status=0/SUCCESS)
 Main PID: 14377 (code=exited, status=0/SUCCESS)
    Tasks: 10
   CGroup: /system.slice/bacchus.service
           ├─14381 /usr/bin/python2 /usr/bin/celery -A bacchus beat -l info -S django --workdir /opt/bacchus
           ├─14383 /usr/bin/python2 /usr/bin/celery -A bacchus flower --broker=amqp://bacchus:test@ob@localhost:5672/bacchus --basic_auth=admin:test@ob --...
           ├─14387 python /opt/bacchus/manage.py runserver 127.0.0.1:8080
           └─14440 /usr/bin/python /opt/bacchus/manage.py runserver 127.0.0.1:8080

Jul 10 09:35:49 cs-test3.bu.edu systemd[1]: Starting Bacchus Service...
Jul 10 09:35:49 cs-test3.bu.edu bash[14377]: [worker] running with pid 14379
Jul 10 09:35:49 cs-test3.bu.edu bash[14377]: [beat] running with pid 14381
Jul 10 09:35:49 cs-test3.bu.edu bash[14377]: [flower] running with pid 14383
Jul 10 09:35:49 cs-test3.bu.edu bash[14377]: [server] running with pid 14387
Jul 10 09:35:49 cs-test3.bu.edu systemd[1]: Started Bacchus Service.
Jul 10 09:35:50 cs-test3.bu.edu python2[14379]: detected unhandled Python exception in '/usr/bin/celery'
[root@cs-test3 logs]# uname -a
Linux cs-test3.bu.edu 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@cs-test3 logs]#

[bacchus-logs.zip](https://github.com/openbacchus/bacchus/files/2181844/bacchus-logs.zip)

Please advise what else i can send or try- thanks!
Steve 
nadas@bu.edu
stephen.nadas@gmail.com

**Comment by openbacchus** [comment]
Hi,

Similar issue was logged before. Could you please try updating the celery ?

# pip install --upgrade celery

**Comment by sjnadas** [comment]
Hi, 

Thanks, that upgrades celery from 4.0.2 to 4.2.0 and gets by this issue. I'm a little confused because I ran the install earlier yesterday and I was under the impression it was getting the latest versions. But okay. 

I now see cert errors bcos of the self signed (i'll get a good cert & install it).  I also see "502 bad gateway" and "400 bad requests - this says it is https traffic to http".  I don't understand the 502 yet. 

Thanks, Steve

**Comment by openbacchus** [comment]
Hi,

Nice to hear that was resolved.

For 502, this might be selinux that is blocking nginx to listen on 443 or django on 8080. Either disable selinux or grant the privileges to bacchus and nginx user.

**Comment by sjnadas** [comment]
Hi, 
yes, selinux related ussues.  i've got to logging into openbacchus and am at the create a manager step.  the ovirt api works when running a test script on the fqdn machine but the vm where openbacchus is installed encounters an issue (says can't find a route for fqdn::443)...
