### ISSUE TITLE
Unnecessary steps on Backup a powered down VM

### ISSUE THREAD

**Issue by xandradx** [openbacchus/bacchus#3]
Currently, the process for a powered up and powered down vm, is the same.

The correct process for backup a powered down vm, it's just to export the VM, there's no need to take a SnapShot, clone and export.

**Comment by niyazielvan** [comment]
When you export the powered down VM directly, you will block it until the export process completes. (e.g. you can not power it on) This is not intended behavior of a backup solution. We should not affect  the availability of a VM while backing it up. So from the availability point of view, correct process is taking a snapshot in both states.

**Comment by xandradx** [comment]
This is true while the VM disks are on a locked state, this also happened when you create a SS, and when you create a Clone. 

But I respect the opinion.
