### ISSUE TITLE
Project Roadmap ?

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [openbacchus/bacchus#5]
Hello.

Do you have a road map for the project? What to expect changes in the project and when?

**Comment by niyazielvan** [comment]
Hi Aleksey,

Are you looking for something specific ?

My initial intention was to build an easy to use backup solution for oVirt. It's not fully implemented yet. Final product will have  basic functionalities like, backup/restore, scheduling, retention periods, (maybe backup to tape). I am open for feature requests. Please let me know if you need something specific.

For now, I am the only one developing the project, so it takes some time to make things work.

**Comment by niyazielvan** [comment]
closing the issue.
