### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by matonb** [openbacchus/bacchus#6]
I'm just trying/testing openbacchaus.

First VM backup seems to be running fine, however the time displayed in running tasks is two hours ahead of the server (both ovirt and machine openbacchus is running on).

Where / how to I check the time zone ?

Thanks

**Comment by bacchus-co** [comment]
You need change the ### TIME_ZONE parameter in ### bacchus/settings.py file. However, changing the timezone will affect the scheduled jobs. You may delete and define the schedules again.
Please let me know if this helps.

**Comment by matonb** [comment]
Yup, that fixed that problem thanks.
